---
name: test-pypi

on:  # yamllint disable-line rule:truthy
  push:
    # Publish `main` as to test.pypi.org
    branches:
      - main

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'test-pypi upload'

jobs:
  pypi-publish:
    name: Upload commit to PyPI
    runs-on: ubuntu-latest
    environment:
      name: test-pypi
      url: https://test.pypi.org/p/cowrie
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      # retrieve your distributions here

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_COWRIE_TEST }}
          repository-url: https://test.pypi.org/cowrie/
